FROM golang:1.17

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download
RUN go mod verify

ENV CELL_DBADDR="celldb"
ENV CELL_DBNAME="CELLDB"
ENV CELL_DBPASS="cellpass123"
ENV CELL_DBPROT="tcp"
ENV CELL_DBUSER="celluser"
ENV CELL_APIPORT="8080"
ENV CELL_APITYPE="2"
ENV CELL_DBTYPE="1"
ENV CELL_REPOTYPE="2"

COPY . .

RUN go build ./cmd/api/main.go

EXPOSE 8080

ENTRYPOINT "/app/main"
