version: '3.8'

services:

  cellapi:
    image: cellapi_dbg:1.0
    container_name: icellapi_dbg
    build:
      context: ../
      dockerfile: docker/Dockerfile.api.debug
    environment:
      CELL_DBADDR: celldb
      CELL_DBNAME: CELLDB
      CELL_DBPASS: cellpass123
      CELL_DBPROT: tcp
      CELL_DBUSER: celluser
      CELL_APIPORT: 8080
      CELL_APITYPE: 1
      CELL_DBTYPE: 1
      CELL_REPOTYPE: 1
    ports:
      - 8880:8080
      - 2345:2345
    networks:
      - cellnet_dbg

  celldb:
    image: celldb_dbg:1.0
    container_name: icelldb_dbg
    build:
      context: ../
      dockerfile: docker/Dockerfile.mysql
    environment:
      MYSQL_DATABASE: CELLDB
      MYSQL_USER: celluser
      MYSQL_PASSWORD: cellpass123
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3310:3306
    networks:
      - cellnet_dbg

networks:
  cellnet_dbg:
