version: '3'

services:

  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example
      POSTGRES_DB: MyDatabase
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
