FROM mysql:8.0

ENV MYSQL_DATABASE="CELLDB"
ENV MYSQL_USER="celluser"
ENV MYSQL_PASSWORD="cellpass123"
ENV MYSQL_ROOT_PASSWORD="toor"

# MySQL will initialize DB using files inside /docker-entrypoint-initdb.d
ADD ./migration/dump.sql /docker-entrypoint-initdb.d

EXPOSE 3306

CMD ["mysqld"]
