version: '3.8'

services:

  cellapi:
    image: cellapi:2.0
    container_name: icellapi
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - 8880:8080
    networks:
      - cellnet

  celldb:
    image: celldb:2.0
    container_name: icelldb
    build:
      context: .
      dockerfile: docker/Dockerfile.mysql
    ports:
      - 3310:3306
    networks:
      - cellnet

networks:
  cellnet:
