CREATE DATABASE IF NOT EXISTS `CELLDB`;
USE `CELLDB`;

CREATE TABLE IF NOT EXISTS `CELLPHONE` (
    `ID` int(10) NOT NULL AUTO_INCREMENT,
    `PROVIDER_ID` int(10) NOT NULL,
    `NUMBER` varchar(50) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `PROVIDER` (
    `ID` int(10) NOT NULL AUTO_INCREMENT,
    `NAME` varchar(100),
    `TOTAL` int(10) NOT NULL DEFAULT 0,
    PRIMARY KEY (`ID`)
);

ALTER TABLE `CELLPHONE`
ADD CONSTRAINT `FK_PROVIDER_CELLPHONE`
FOREIGN KEY (`PROVIDER_ID`) REFERENCES `PROVIDER`(`ID`);
